# This file was generated by GoReleaser. DO NOT EDIT.
cask "hashi" do
  name "hashi"
  desc "Git worktree + tmux session manager"
  homepage "https://github.com/wasabi0522/hashi"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hashi"

  on_macos do
    on_intel do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_darwin_amd64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "e17ab4ccaf76c59eb5b86cc9368cafc2ae55e73c87f640c8ab7d072baceff6c4"
    end
    on_arm do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_darwin_arm64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "f747a8be664d4e3aa46428b46e1addf84b929496abdba745169807fad9283ef6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_linux_amd64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "619f268ea7aa87b92af0ff91a608dd05495882b4331f52b564212eeb822f35c9"
    end
    on_arm do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_linux_arm64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "7302b2f3909f59fd11e4f8d0650940a9855c61965ec9feae503603b232c50516"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hashi"]
    end
  end

  # No zap stanza required
end
