# This file was generated by GoReleaser. DO NOT EDIT.
cask "hashi" do
  name "hashi"
  desc "Git worktree + tmux session manager"
  homepage "https://github.com/wasabi0522/hashi"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hashi"

  on_macos do
    on_intel do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_darwin_amd64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "eb22a0c158e8385745e9ae4a7e5ae1de64a62d3c7e17edcb78c57acba7eab307"
    end
    on_arm do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_darwin_arm64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "3c3c4ea3715f9c44de1ffa0597bb83871750ae953d213c4314ab017e2a26bffb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_linux_amd64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "8de8952ced166cdea356d0333f512f916dc6aecc5e995a54c9e1301ef00099c6"
    end
    on_arm do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_linux_arm64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "58a1759fb129af9d4098719e488c898bd7e165ce79a168ab42ac538f103e436b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hashi"]
    end
  end

  # No zap stanza required
end
