# This file was generated by GoReleaser. DO NOT EDIT.
cask "hashi" do
  name "hashi"
  desc "Git worktree + tmux session manager"
  homepage "https://github.com/wasabi0522/hashi"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hashi"

  on_macos do
    on_intel do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_darwin_amd64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "943796760f531700dbf7260b90e1f2097d40231f306e5cbc03082095304cd180"
    end
    on_arm do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_darwin_arm64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "111a917b265fa0430d1e974af3030aad5b1ecfd5c4d4af4072b34797cf309b8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_linux_amd64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "351e760f40bebb28fb4df37ee340fba5eeedc005475fcf5fc3e50c1ba3b3562c"
    end
    on_arm do
      url "https://github.com/wasabi0522/hashi/releases/download/v#{version}/hashi_linux_arm64.tar.gz",
        verified: "github.com/wasabi0522/hashi"
      sha256 "d8b69a2c8e426ea54334560577e746496924a8aaee025d34b918deb7f6a18468"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hashi"]
    end
  end

  # No zap stanza required
end
